Algoritmo "UN3.3-EXERC3.2"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/09/2022
Var
// Seção de Declarações das variáveis 
contador,soma:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
para contador de 1 ate 100 faca
     soma <- soma + contador
fimpara

escreval(soma)

Fimalgoritmo