Algoritmo "AULA3-ex1-B"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/08/2022
Var
// Seção de Declarações das variáveis 
sexo:caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite o sexo (m ou f):")
leia(sexo)
se (sexo="m") ou (sexo="f") entao
   escreval("Sexo válido")
   senao
        escreval("Dado incorreto")
fimse

Fimalgoritmo